version: "3.9"

services:
  db:
    image: postgres:17-alpine
    container_name: galactic_swords_db
    restart: always
    environment:
      POSTGRES_DB: galactic_swords
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: galactic_swords_app
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/galactic_swords
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}

      SPRING_FLYWAY_ENABLED: "true"
    ports:
      - "8080:8080"

volumes:
  postgres_data:
